Repository christina-cook/stretch-project, pull requests merged in 2021-02, with the labels that each got.

#9 Feature/initial firebase setup
  database.rules.json
  env.local
  package-lock.json
  package.json
  src/contexts/AuthContext.js
  src/contexts/firebase.js
Labels: documentation

#13 Feature/dashboard
  src/components/App.js
  src/components/ColorCard.js
  src/components/Dashboard.js
  src/components/ImageCard.js
  src/components/ResultsDisplay.js
  src/contexts/ApiCalls.js
Labels: enhancement

#15 Feature form styling
  package-lock.json
  src/assets/form/facebook.png
  src/assets/form/github.png
  src/assets/form/google.png
  src/components/App.js
  src/components/Login.js
  src/components/Signup.css
  src/components/Signup.js
Labels: enhancement

#22 testing-ar
  cypress/integration/about.spec.js
  cypress/integration/error.spec.js
  cypress/integration/footer.spec.js
  cypress/integration/header.spec.js
  cypress/integration/loading.spec.js
  src/components/About.js
  src/components/App.js
  src/components/Error.js
  src/components/Footer.js
  src/components/Header.js
  src/components/Loading.js
Labels: enhancement

#23 Testing/dashboard
  cypress/fixtures/example.json
  cypress/fixtures/imageData.json
  cypress/integration/dashboard.spec.js
  cypress/integration/examples/actions.spec.js
  cypress/integration/examples/aliasing.spec.js
  cypress/integration/examples/assertions.spec.js
  cypress/integration/examples/connectors.spec.js
  cypress/integration/examples/cookies.spec.js
  cypress/integration/examples/cypress_api.spec.js
  cypress/integration/examples/files.spec.js
  cypress/integration/examples/local_storage.spec.js
  cypress/integration/examples/location.spec.js
  cypress/integration/examples/misc.spec.js
  cypress/integration/examples/navigation.spec.js
  cypress/integration/examples/network_requests.spec.js
  cypress/integration/examples/querying.spec.js
  cypress/integration/examples/spies_stubs_clocks.spec.js
  cypress/integration/examples/traversal.spec.js
  cypress/integration/examples/utilities.spec.js
  cypress/integration/examples/viewport.spec.js
  cypress/integration/examples/waiting.spec.js
  cypress/integration/examples/window.spec.js
  cypress/integration/resultsDisplay.spec.js
  package-lock.json
  src/components/ColorCard.js
  src/components/ImageCard.js
Labels: enhancement

#25 Feature/login kh
  cypress/integration/resultsDisplay.spec.js
  src/components/Dashboard.js
  src/components/Header.js
  src/components/Login.js
  src/components/Signup.js
  src/contexts/AuthContext.js
Labels: enhancement

#27 Add card styling to dashboard
  src/components/ColorCard.js
  src/components/Dashboard.css
  src/components/Dashboard.js
  src/components/colorCardInfo.js
Labels: enhancement

#28 Feature outside auth
  src/components/Login.js
  src/components/Signup.js
  src/contexts/AuthContext.js
  src/contexts/firebase.js
Labels: enhancement

#30 Testing/login
  cypress/fixtures/userLoginRes.json
  cypress/integration/login.spec.js
  cypress/integration/signup.spec.js
  cypress/integration/signup_spec.js
  src/components/Login.js
  src/components/Signup.js
Labels: documentation, enhancement
